### ISSUE TITLE
BRFv4_JS_trial.js in Web Worker mode

### ISSUE THREAD

**Issue by przemos** [Tastenkunst/brfv4_javascript_examples#1]
Hi, 
we would like to use this fantastic lib in a web worker configuration due to cpu overhead caused by face detection. Unfortunately, even if ENVIRONMENT = 'WORKER' config is set to true, we are getting require function not found error. It seems that the lib tries to use require() to fetch something but it is not available inside web worker...

**Comment by MarcelKlammer** [comment]
If you could send me a link to a minimal setup like that, I could debug and see how to get that working.

**Comment by przemos** [comment]
https://gist.github.com/przemos/4c9c1ac250b1b315f6e80da570bc5148

It is failing on init.

**Comment by MarcelKlammer** [comment]
Could you point me to some explanation on how to setup a worker?

**Comment by przemos** [comment]
<script>
var w = new Worker('path to the script in gist')
</script>

**Comment by MarcelKlammer** [comment]
Found the issue and will look into it next week, since I'm out of office for three days.

**Comment by przemos** [comment]
thank you

**Comment by brandon-vb** [comment]
Was there ever a resolution to this issue?

**Comment by ramkumardnagarajan** [comment]
@MarcelKlammer I'm facing same issue. are you fixed this issue.

**Comment by MarcelKlammer** [comment]
Nope. No web worker support for the foreseeable future, since the change in the structure is not trivial.
