### ISSUE TITLE
camera take too much time to load

### ISSUE THREAD

**Issue by AlaaElZein** [Tastenkunst/brfv4_javascript_examples#10]
Hello,
I am using the blink detection on my code so i need to open the camera,
but when we have to open the camera with brfv4 on chrome for the first time it takes too much time to load,
What is the solution?
Regards,

**Comment by MarcelKlammer** [comment]
How long does it take?
For me, eg. on this page:
https://tastenkunst.s3.amazonaws.com/demos/brfv4/test_fast_chrome/index.html
it loads quite fast.
