### ISSUE TITLE
How to generate the brfv4Example.faceTextures?

### ISSUE THREAD

**Issue by lesrpo** [Tastenkunst/brfv4_javascript_examples#13]
Hello,

I've been going around with this, I would like to know how can I generate more faceTexture objects, I am taking a picture from the camera and getting the vertices of it as well, but it never overlap the pictures. 

Thank you

**Comment by MarcelKlammer** [comment]
Depends on what you would like to add.

1. actual face:

Track that face with BRFv4. Then crop the face to whatever size, you can even use the input camera image. Then "record" the tracked 68 points for that image and calculate the normalized values (0.0 to 1.0) for the image you are saving. 

So if you want to use a 640x480 camera image, on click freeze that image and read the 68 points. Their values would need to be normalized like this: x = x / 640.0 and y = y / 480.

Then you can use that frozen image that you saved as texture and the normalized values as uv data.

2. a mask overlay that can't be tracked.

Open the face texture that comes with the examples in Photoshop and paint above that face whatever you want. Save your painting and load that as face texture.
