### ISSUE TITLE
SSL certificate distrust warning in Chrome

### ISSUE THREAD

**Issue by wookee9** [Tastenkunst/brfv4_javascript_examples#15]
This console warning notification has recently started appearing in Chrome when running BRFv4:

```
! The SSL certificate used to load resources from https://www.beyond-reality-face.com
will be distrusted in M70. Once distrusted, users will be prevented from loading 
these resources. See https://g.co/chrome/symantecpkicerts for more information.
```

This is using BRFv4_JS_CC260917_v4.0.1_commercial.js

See: https://security.googleblog.com/2017/09/chromes-plan-to-distrust-symantec.html

It appears that Chrome is planning to distrust a large number of SSL certs issued by Symantec and subsidiary companies. And seemingly, the cert used by the BRF licence-checking server, is one of those affected.

In Chrome, use of certain features like the webcam requires a secure context; typically content served via an https or localhost connection. If / when this certificate stops being seen as 'secure' by Chrome 66 in March 2018, it seems likely that this will fail the secure context check, which may in turn prevent the webcam and BRF from working altogether. Is this correct?

Can you please look into this issue as a matter of urgency?

**Comment by MarcelKlammer** [comment]
Hi and thanks for bringing that up.

The certificate on https://www.beyond-reality-face.com

was issued on 24th of July 2017 and must be renewed before 24th August 2018.

"Starting with Chrome 66 (March 2018), Chrome will remove trust in Symantec-issued certificates issued prior to June 1, 2016".

Our site should not be affected by the release of Chrome 66.

"Additionally, by December 1, 2017, Symantec will transition issuance and operation of publicly-trusted certificates to DigiCert infrastructure, and certificates issued from the old Symantec infrastructure after this date will not be trusted in Chrome."

"Around the week of October 23, 2018, Chrome 70 will be released, which will fully remove trust in Symantec’s old infrastructure and all of the certificates it has issued."

Our certificate must be renewed in 2018, on the new Symantec platform, well before the release of Chrome 70 in October 2018.

So, from my point of view we will dodge that one with our certificate renewal in August 2018.

Best Regards
Marcel
