### ISSUE TITLE
CPU load rapidly increased to peak while tracking face

### ISSUE THREAD

**Issue by ramkumardnagarajan** [Tastenkunst/brfv4_javascript_examples#16]
@MarcelKlammer  CPU load and memory rapidly increased while start the face tracking. In low configuration machines page reload occur due to CPU  overload. You have any idea on this.

**Comment by MarcelKlammer** [comment]
Could you be more specific about that environments you are talking about?

**Comment by ramkumardnagarajan** [comment]
@MarcelKlammer , I have just tested face tracking in browser ('minimalWebcam.html'). while start tracking the face the cpu load increased rapidly
![brfv4-issue](https://user-images.githubusercontent.com/27269162/34145591-c2a6825c-e4bc-11e7-8cbc-a5fccb1c2c5a.png)

**Comment by MarcelKlammer** [comment]
That's to be expected. What else do you expect from an advanced face tracker? I find the new Firefox to have 50% of the CPU load of Chrome, though.
