### ISSUE TITLE
Getting array of points?

### ISSUE THREAD

**Issue by YeisonVelez11** [Tastenkunst/brfv4_javascript_examples#2]
I am trying to get the array points detected in a single picture of a person. How can get the points?

**Comment by MarcelKlammer** [comment]
Use the BRFv4SetupPicture.js instead of BRFv4SetupWebcam.js
Load your image and read the points from the BRFFace object.

**Comment by YeisonVelez11** [comment]
I want to thank for this powerful library. I would like to try to recognize the points of the face. But I would like to do it with the most minimalist possible so as not to consume so many resources. I'm trying to recognize the points of a photo that I captured with my cell phone. The image size will be 280px x 280px. To put your code in a cell thanks to the ionic framework, this is delayed in some cell phones around 40 seconds. How can I optimize your code to work with the minimum ?.

This is the code that I have modified just so you can see how I am doing it. (it will not work). I have based myself on the minimalImage.html file

https://jsfiddle.net/7wpd6n75/
