### ISSUE TITLE
Facial Landmarks

### ISSUE THREAD

**Issue by enijar** [Tastenkunst/brfv4_javascript_examples#21]
Is it possible to get the position (x, y) of facial landmarks, for example left eye, right eye, nose and mouth?

**Comment by MarcelKlammer** [comment]
Sure, these are the facial landmarks:

https://github.com/Tastenkunst/brfv4_javascript_examples/blob/master/brfv4_landmarks.jpg

The landmarks have x,y coordinates according to the image you analyze.

**Comment by enijar** [comment]
@MarcelKlammer Ah, didn't see that image – thanks!
