### ISSUE TITLE
support for raspberry PI?

### ISSUE THREAD

**Issue by ianni67** [Tastenkunst/brfv4_javascript_examples#24]
Great piece of software, working perfectly and very stable.
Any hope for a working version for raspberry PI? My raspbian supports chromium-browser but currently does not load the webassembly code from your library. 
I would love letting my PI "see" me...

**Comment by MarcelKlammer** [comment]
Thank you. Try the asm.js version to see whether the webcam is supported. I've no idea of what's supported by Chromium on PI.

**Comment by ianni67** [comment]
the javascript console of chromium says that wasm failed to load ("false loading wasm") while checking for webassembly. Is there any hope that this issue will be taken into consideration?
The webcam is indeed supported by the PI, and it is working with chromium (with other javascripts).
