### ISSUE TITLE
Loading 3D Model

### ISSUE THREAD

**Issue by devmode2018** [Tastenkunst/brfv4_javascript_examples#25]
Hi,
Thank you for this amazing work first of all.
my question it is how i can load the 3D model ;as i see you load it as json. ho wit can be done .I tried some .obj to json converter but nothing .
Thank you

**Comment by devmode2018** [comment]
Any answer please ??

**Comment by MarcelKlammer** [comment]
ThreeJS: https://threejs.org/
ThreeJS editor: https://threejs.org/editor/

You will have to look into ThreeJS and how it loads files etc. The editor can load obj files and export json files. But there are tons of examples on how to load other file formats in ThreeJS.
