### ISSUE TITLE
Safari - iOS 11 (on most devices) Web Assembly support check passes but SDK hangs on WASM setup

### ISSUE THREAD

**Issue by pathiller** [Tastenkunst/brfv4_javascript_examples#26]
When observing on Safari the WASM implementation gets stuck in the check for `brfv4.sdkReady`.
Switching out for ASMJS seems to work in these cases but I'm currently working on finding a way to check for WASM support beyond checkout typeof 'object' as it returns true in all of these cases.

Have you noticed this?

**Comment by MarcelKlammer** [comment]
https://www.scirra.com/blog/218/apple-broke-webassembly-and-are-leaving-it-broken

**Comment by pathiller** [comment]
Thanks @MarcelKlammer, used this from the article to detect broken web assembly support and load asmjs - 

[https://github.com/brion/min-wasm-fail/blob/master/min-wasm-fail.js](url)
