### ISSUE TITLE
Uncought abort("Cannot enlarge memory arrays. Either compile with -s TOTAL_MEMORY=X

### ISSUE THREAD

**Issue by ruslan-mystore** [Tastenkunst/brfv4_javascript_examples#27]
I'm using brfv4 in react application.
Tested the the app for a few days and got this error , which stopped the plugin !

P.S: I want to thank to the creator of this amazing work!
![11](https://user-images.githubusercontent.com/32633310/36476066-0f681570-16fd-11e8-8d91-f061142f2e7d.png)

**Comment by MarcelKlammer** [comment]
Usually this type of error only pops up when only one file was updated, either the .js or .mem file. 
So please update to the newest version, which also includes a WebAssembly version.

Which Browser and which system is it?

**Comment by ruslan-mystore** [comment]
@MarcelKlammer 
The error occurred both on Linux and Windows . Chrome browser
The app just working fine, but after few days the app throwing this error.
I will check the newest version

**Comment by ruslan-mystore** [comment]
Updated to the newest version and got this error after the app worked for a day:
![22](https://user-images.githubusercontent.com/32633310/36531620-d044885c-17be-11e8-9926-d5667aa578e1.png)

**Comment by MarcelKlammer** [comment]
I have no idea how reproduce that. This is even after the initialization. How can I reproduce that. Can you share some code?

**Comment by hjrhjr** [comment]
i have save problem,after brvf run long time(more then three hours and camera resolution 720 *960 )， Memory leak? and how can catch this errror or brvf fire event,  let page auto reload.
