### ISSUE TITLE
Emotion Tracking Video Real Time

### ISSUE THREAD

**Issue by FlorianHergo** [Tastenkunst/brfv4_javascript_examples#28]
Hello,

We would like to know if your project will detect the emotion of the person on the video: Happy, sad, etc ...

Thanks
Best regards,

**Comment by MarcelKlammer** [comment]
Nope, it’s „only“ a facial feature tracker and does not include any emotion tracking.

**Comment by luiscosio** [comment]
@FlorianHergo You need to use something like Amazon Rekognition.

We are using BRFV4 + Amazon Rekognition to achieve something like that:

![image](https://user-images.githubusercontent.com/1666/40087096-be97dfee-5866-11e8-88ba-53d5ec854e5c.png)
