### ISSUE TITLE
Mask two faces

### ISSUE THREAD

**Issue by luiscosio** [Tastenkunst/brfv4_javascript_examples#29]
Hello!

Is it possible to mask more than one face?

What would be the necessary changes needed to be done to ´minimalWebcamPNGOverlay.html´ to mask more than one face?

Any pointer would be greatly appreciated.

**Comment by MarcelKlammer** [comment]
Duplicate the div id="mask" and in track faces, getElementById the second mask and have the second tracked face (i==1) prosition the second mask?

**Comment by luiscosio** [comment]
@MarcelKlammer "Duplicate the"

I'm sorry, I think you skipped what I needed to duplicate, haha.

**Comment by luiscosio** [comment]
@MarcelKlammer Thank you so much, I will test it and let you know.
