### ISSUE TITLE
Detect face in an image, using the least possible resources.

### ISSUE THREAD

**Issue by YeisonVelez11** [Tastenkunst/brfv4_javascript_examples#3]
I want to thank for this powerful library. I would like to try to recognize the points of the face. But I would like to do it with the most minimalist possible so as not to consume so many resources. I'm trying to recognize the points of a photo that I captured with my cell phone. The image size will be 280px x 280px. To put your code in a cell thanks to the ionic framework, this is delayed in some cell phones around 40 seconds. How can I optimize your code to work with the minimum ?.

This is the code that I have modified just so you can see how I am doing it. (it will not work). I have based myself on the minimalImage.html file

https://jsfiddle.net/7wpd6n75/

**Comment by MarcelKlammer** [comment]
hmm. How many 280x280 cells of faces do you have? Do you reload and initialize BRF for every cell or do you reuse the BRFManager instance? I'm not sure whether BRF is JSFiddle compatible.

**Comment by YeisonVelez11** [comment]
http://i.imgur.com/IFnD8tH.jpg  this is the image that I am using. Then use the code as you see it on that link. https://jsfiddle.net/uwdtx8pn/   (This will not work, I just put it so you can see the code I'm using. I will always use any image of 280 px x 280px and with a program I reduce the size.)

**Comment by YeisonVelez11** [comment]
@MarcelKlammer ??
