### ISSUE TITLE
BRF Library taking more time to load on mobile devices.

### ISSUE THREAD

**Issue by Satya593** [Tastenkunst/brfv4_javascript_examples#30]
BRF Library taking more time to load on mobile devices - can you reduce the size of the library OR use any compression technology like Gzip to load faster on mobile devices.

**Comment by MarcelKlammer** [comment]
BRF includes descriptor files, which are essential for the tracking. This data is already compressed by over 50% and can't be reduced further (compression). 

Removing tracking stages is an option, currently the file is 9.1mb and could be reduced to 7.6mb or 6.0mb. But this will also reduce accuracy to a great deal, so is only suitable when you don't need the tracking to be most accurate.

Reducing the tracking stages is available to paying customers only.
