### ISSUE TITLE
Obtaining True 3D Information

### ISSUE THREAD

**Issue by Xen0phobe** [Tastenkunst/brfv4_javascript_examples#33]
I'm trying to get 3D vertex information from the Candide3 mask overlay so that I can parse it into a 
Wavefront .obj file and then subsequently import it into Blender. I've read the CandideVertices and CandideTriangles arrays each time the canvas updates and noticed that the vertices array has a length of 226. If the array contains 3D coordinates (X, Y, Z) then it would stand to reason that length of array should be divisible by 3 -- it isn't. The API documentation leads me to believe that it should be possible to obtain 3D facial coordinates, ["The candide 3 model vertices. Can be used to visualize the 3D position, scaling and rotation."](https://tastenkunst.github.io/brfv4_docs/#candideVertices) Is there somewhere within the code I can snag these coordinates, or, if they're never actually calculated in 3D, easily convert the 2D coordinates of the Candide3 face into three dimensions?

Thank you for your time and the wonderful program you created.

**Comment by MarcelKlammer** [comment]
Hi there,

the Candide3 overlay is acutally calculated in 3D, but since it's just a visualization we projected the 3d cords to 2d vertices. BRFv4 will not get any API to retrieve the 3d values. Maybe BRFv5 will, but it won't be released before 2019.
