### ISSUE TITLE
Runtime error, memory access out of bounds (WASM)

### ISSUE THREAD

**Issue by jasonmayes** [Tastenkunst/brfv4_javascript_examples#38]
I am getting the following error (I have tried updating to latest) which only started happening recently - and my code has not changed.  The only thing that may have changed is Chrome which updated to latest version by itself.  It seems to perform one face recognition and then bail with the following:

wasm-0000006e-37:83 Uncaught RuntimeError: memory access out of bounds
    at wasm-function[37]:155
    at wasm-function[29]:19
    at wasm-function[194]:100
    at wasm-function[92]:108
    at wasm-function[133]:449
    at wasm-function[358]:344
    at wasm-function[875]:6
    at wasm-function[888]:531
    at wasm-function[398]:16
    at Module.dynCall_viii

Can anyone advise/help. I have tried everything. Sometimes the error shows, sometimes it fails silently but the effect is the same - calls to update fail silently and face tracking stops working.

**Comment by MarcelKlammer** [comment]
The library should be set to allow memory growth. Do you have a test link for me?

**Comment by jasonmayes** [comment]
I am running on localhost right now unfortunately. What i find particularly odd is if I have your website demo open in another tab, I dont get the error and everything works fine... I dont even know how that is possible but it is consistent in working when I have your JS demo open in other chrome tab. Maybe I can setup a Google hangout to walk through this with you as not on a public server as just testing on localhost.

**Comment by MarcelKlammer** [comment]
Please add me in Skype. I sent you an email with my handle. The version you are using is actually not intended to be used by you. I guess you work for Peter and jam?

**Comment by jasonmayes** [comment]
I am working with them on that project. I was seeing if that fixed the issue or not. I was using trial before Trial gives me same results.

**Comment by jasonmayes** [comment]
PS added you on Skype.

**Comment by jasonmayes** [comment]
Any update on this? I am still getting the error on trial version of code.

**Comment by MarcelKlammer** [comment]
I found no clue of why an out of bounds should be triggered. Memory growth should be enabled.
Anyway I uploaded a current export of the trial version to this repo. So please use that as a reference.

If the error still exists, then the only way I could try to help is by looking at the source code of your project, which you would need to upload somewere. You can send me the link via Skype if you want to.

**Comment by jasonmayes** [comment]
Ok thanks. I think for now I shall have to switch to a different library. I am going to try Chrome's built in one for now until I figure out what is causing the memory issue. Thanks for your help!
