### ISSUE TITLE
It's hard to run an example outside of the demo.

### ISSUE THREAD

**Issue by alamboley** [Tastenkunst/brfv4_javascript_examples#39]
Hey,

I'm just trying to setup a face-swap demo outside of the `brfv4_javascript_examples`. So I tried to change the minimalWebcam with the code provided for the face-swap but it's a total nightmare.

`BRFv4Demo` and `BRFv4SetupExample` add so many things you don't have in `BRFv4DemoMinimalWebcam`... Then copy some code from `face_swap_two_faces.js` but having errors with properties like `draw`.

Did I miss an obvious way to just copy/paste some code in a minimal example !?

**Comment by MarcelKlammer** [comment]
Nightmare is not a word that motivates me. The all-in-one demo uses CreateJS to draw stuff, and because it's all-in-one, it loads a bunch of stuff.

Anyway. I've just commited a minimalWebcamFaceSwap.html for you.

**Comment by alamboley** [comment]
Many thanks sir! It's easier to see how things work now.
