### ISSUE TITLE
video feed

### ISSUE THREAD

**Issue by floatingworld3** [Tastenkunst/brfv4_javascript_examples#42]
sorry i may have asked this question elsewhere but I lost the thread. How do I use brf to track a face in a video rather than a webcam?

**Comment by ghost** [comment]
The way I've done it is by grabbing the video's pixels and painting them onto a canvas. I then pass the canvas into the BRF manager for inference.

Here's some psuedocode:

```js
const $video = document.querySelector('#video-to-infer-on')
const $canvas = document.querySelector('#canvas-to-draw-into')
const context = $canvas.getContext('2d')
// brf = whatever variable you store the brf object into
// brfManager = whatever variable you store the brf manager into

// Paint video into canvas...you could also paint another canvas into the canvas, for example, photorealistic unity games
context.drawImage($video, 0, 0, brf.resolution.width, brf.resolution.height)

// Get faces
brfManager.update(context.getImageData(0, 0, brf.resolution.width, brf.resolution.height).data)
const faces = brfManager.getFaces()
```

**Comment by floatingworld3** [comment]
Thanks for the pseudo code...could you give a specific instance  for "#canvas-to-draw-into" ?
Is  #video-to-infer-on'  the path name to the video?
Thanks again

**Comment by vkasojhaa** [comment]
@floatingworld3 did you get the face tracker working on video?

**Comment by floatingworld3** [comment]
Hello vikas,

Sorry for the late reply.
No I did not get tracker working on video.
Do you have some sample code?

David
