### ISSUE TITLE
need help for integrate with react js application 

### ISSUE THREAD

**Issue by kamaldlk** [Tastenkunst/brfv4_javascript_examples#45]

**Comment by eedsilva** [comment]
React JS and React Native :)

**Comment by kamaldlk** [comment]
React JS

**Comment by MarcelKlammer** [comment]
I didn't work with React yet. I'm using Vue.js for my wep apps.
What challenges are you facing?

**Comment by kamaldlk** [comment]
@MarcelKlammer thanks for replying even I don't have an idea where I should start, we have licenses for brfv4 please give me some samples in react

**Comment by MarcelKlammer** [comment]
Which company do you represent, if you claim to have a commercial license?
Also: As said before: I never worked with React yet. I use Vue.js for web apps. So I can't give you any React examples.

**Comment by eedsilva** [comment]
How do you use it with Vue.js? What is the npm package?

**Comment by kamaldlk** [comment]
@MarcelKlammer oic from India (Vasan)

**Comment by MarcelKlammer** [comment]
There is no npm package. You need to load the scripts and check for WebAssembly support before embedding the correct script (either wasm or asmjs).

**Comment by eedsilva** [comment]
In this case it is doable in React JS, but isn’t in React Native (my guess)

**Comment by kamaldlk** [comment]
@eedsilva thanks if u have sample share with me. if i done today, I'll share with u all

**Comment by eedsilva** [comment]
I’ll let you guys know if I succeed :)

**Comment by super-dog-human** [comment]
Hi there, I'm using BRFv4 (trial ver.) with Web Worker in my React.js  app.
FYI, Here is some codes 😉 
https://github.com/SuperDogHuman/teraconn/blob/master/js/lessonRecorder/index.jsx
https://github.com/SuperDogHuman/teraconn/blob/master/js/lessonRecorder/utils/faceDetector.js
https://github.com/SuperDogHuman/teraconn/blob/master/js/lessonRecorder/utils/faceDetectionWorker.js

**Comment by kamaldlk** [comment]
i tried

**Comment by ortuagustin** [comment]
> There is no npm package. You need to load the scripts and check for WebAssembly support before embedding the correct script (either wasm or asmjs).

Can you provide example with Vue js?

**Comment by MarcelKlammer** [comment]
#58 for minimal webworker update.
