### ISSUE TITLE
error's contains brf_asmjs in commercial min.js 

### ISSUE THREAD

**Issue by kamaldlk** [Tastenkunst/brfv4_javascript_examples#46]
@MarcelKlammerI configured eslint in my project brf_asmjs in commercial-min.js showing some lint error I can't able to move in production, please fix that eslint issue it's very urgent :(
![screen shot 2018-12-06 at 8 00 16 am](https://user-images.githubusercontent.com/9652523/49557814-e45e5780-f92e-11e8-9c07-6e101a8ebadb.png)
![screen shot 2018-12-06 at 8 02 24 am](https://user-images.githubusercontent.com/9652523/49557815-e45e5780-f92e-11e8-84a3-18b3099a67d1.png)

**Comment by kamaldlk** [comment]
@MarcelKlammerI configured eslint in my project brf_asmjs in commercial-min.js showing some lint error I can't able to move in production, please fix that eslint issue it's very urgent

**Comment by MarcelKlammer** [comment]
es-lint? remove the file from es-lint handling then...

**Comment by MarcelKlammer** [comment]
Here is how it's done:

https://evanhahn.com/disable-eslint-for-a-file/
