### ISSUE TITLE
What's changed it in v4.2.0?

### ISSUE THREAD

**Issue by whilemouse** [Tastenkunst/brfv4_javascript_examples#49]
Hi. I saw update v4.2.0.
What's changed it?

**Comment by MarcelKlammer** [comment]
v4.2.0 - 21.02.2019:

For BRFv5 we reimplemented Optical Flow. This single component does now replace the BRFv4 version of it.

So basically the Optical Flow needed an overhaul for one of our clients. I also updated all the build tools to keep up to date.

**Comment by whilemouse** [comment]
I confirmed it late. thanks
