### ISSUE TITLE
can not run on ios safari 

### ISSUE THREAD

**Issue by cnjack** [Tastenkunst/brfv4_javascript_examples#5]
Unhandled Promise Rejection: NotAllowedError (DOM Exception 35): The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

```
webcam.onStreamFetched = function(mediaStream) {

	webcam.stream = mediaStream;

	if(webcam.video !== null) {
		webcam.video.srcObject = mediaStream;
		webcam.video.play();
		webcam.onStreamDimensionsAvailable();
	}
};
```

**Comment by MarcelKlammer** [comment]
iOS 10 or iOS 11 beta?

**Comment by cnjack** [comment]
IOS11 beta

**Comment by cnjack** [comment]
Iphone SE

**Comment by MarcelKlammer** [comment]
Tested it last week on my iPad Pro iOS 11 beta and it started. Hope to find some time next week to take a look again.

**Comment by cnjack** [comment]
I will try fix it if I have time~~

**Comment by cnjack** [comment]
NotAllowedError
The user agent (browser) or operating system doesn't allow playback of media in the current context or situation. This may happen, for example, if the browser requires the user to explicitly start media playback by clicking a "play" button.

from [https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play)

**Comment by cnjack** [comment]
I try on my iPad mini 4, it worked!
