### ISSUE TITLE
uv mapping

### ISSUE THREAD

**Issue by whilemouse** [Tastenkunst/brfv4_javascript_examples#51]
Hi. I like your library. thanks.

[advanced - face tracking - face texture overay](https://tastenkunst.github.io/brfv4_javascript_examples/)

I'm intrigued with this. Real face with face image mapping by uv map.
I want real face with 3d model(three.js) by uv map. Is it possible?

**Comment by MarcelKlammer** [comment]
No, I don't think so. You would need to generate a 3d head and put a texture on that head.
Then you would need to mark all the 68 points on that texture and calculate the uv map, which then would be static. Then you could just "overwrite" the texture content like done in the face mapping example... but I doubt this will look any good.

**Comment by whilemouse** [comment]
thanks :)
