### ISSUE TITLE
Turn off camera + disable library

### ISSUE THREAD

**Issue by mschiano** [Tastenkunst/brfv4_javascript_examples#52]
I know I can init the camera/library by doing brfv4Example.init("webcam"); which then turns on the green light for the camera on my macbook pro. 

Is there a way I can de-init the library/camera without doing a hard page reload?

**Comment by MarcelKlammer** [comment]
Well I guess you will need to add a function like this in BRFv4SetupExample.js

`
example.dispose = function() {
	drawing.setUpdateCallback(null);
	imageData.dispose();
}
`

**Comment by mschiano** [comment]
That worked! Thanks for the quick reply!
