### ISSUE TITLE
ios "No camera found"

### ISSUE THREAD

**Issue by Vadekvan** [Tastenkunst/brfv4_javascript_examples#54]
Hello,
When I try your demo on my iPhone everything are OK. But when I donwloaded your examples and run in my xampp, on my iPhone safary alert say "No camera found".

Can be somethink wrong with this warnings?
![warning](https://user-images.githubusercontent.com/16124300/54865878-cb0dd980-4d6c-11e9-8577-d00613fc1751.JPG)

Thank you!!

**Comment by Vadekvan** [comment]
BTW: warnings are from windows PC.

**Comment by MarcelKlammer** [comment]
Maybe it's not working because it's not https.

**Comment by Vadekvan** [comment]
thank you!
