### ISSUE TITLE
Color-libs : Change of color on the lips.

### ISSUE THREAD

**Issue by akshajb** [Tastenkunst/brfv4_javascript_examples#61]
Hey. So I am using the color-libs example, and changing the colour from orange to something else on the lips. But the colour that I give and the colour being rendered have minuscule difference. Any idea how to fix that?

**Comment by akshajb** [comment]
Even the default example doesn't match the EXACT colour that's being rendered.

**Comment by MarcelKlammer** [comment]
That has nothing to do with the tracking, I guess. It's canvas related if anything else.

**Comment by akshajb** [comment]
Thank you for the quick response, stuck in a pinch situation here. 

`draw.drawTriangles(	face.vertices, libTriangles, false, 1.0, color, opacity);				draw.fillTriangles(	face.vertices, libTriangles, false, color, opacity);`

this "color" and the color that renders, are slightly off. Even the oranges in the default example are off  " 0x00a0ff".

I am using Eye Dropper chrome extension to check the values

**Comment by MarcelKlammer** [comment]
And the opacity is set to 1? If not, the color is transparent.

**Comment by akshajb** [comment]
Yes. The opacity is hardcoded right now to 1.

**Comment by MarcelKlammer** [comment]
Well then it's most likely the antialised drawing I guess.
Try to draw a large rect, eg. 100x100 and take the color from the center... I think you will have to live with canvas not rendering perfect colors

**Comment by akshajb** [comment]
Oh so the colors won't be perfect? also what is the clear parameter used for ?

**Comment by MarcelKlammer** [comment]
clearing the canvas I guess.

**Comment by akshajb** [comment]
clearing the canvas before every draw? the changing it from false to true does not really affect anything visually, so was curious

**Comment by MarcelKlammer** [comment]
I have no idea, the code is 2 years old and I'm currently working on the release of BRFv5.

**Comment by akshajb** [comment]
Thank you for your help.
